### ISSUE TITLE
AndrOpen Office: Where is the source code?

### ISSUE THREAD

**Issue by davidhedlund** [androidports/core#2]
I [https://gitlab.com/fdroid/rfp/issues/457#note_54873846 suggested] F-Droid to package AndrOpen Office but we cannot find the source code, can you please give me a link to it?

**Comment by androidports** [comment]
Sorry, AndrOpen Office is closed project. This repository is for AndroPorts: LibreOffice app.

**Comment by davidhedlund** [comment]
@androidports 
* Are you saying that https://github.com/androidports is totally unrelated to AndrOpen Office ?
* Is https://github.com/androidports related to https://f-droid.org/packages/org.documentfoundation.libreoffice/ ?
* Do you want AndroPorts: LibreOffice to be packaged to [F-Droid](http://f-droid.org/)?

**Comment by androidports** [comment]
Some sources related to AndrOpen Office are opened here, i.e. LGPL or MPL.
I don’t know why my app is uploaded to F-Droid as open source.

**Comment by davidhedlund** [comment]
https://github.com/androidports/core/issues/3
